# Generated by Django 5.2.7 on 2025-10-17 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Ambiente',
                'verbose_name_plural': 'Tipos de Ambiente',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('atendente', 'Atendente'), ('gerente', 'Gerente'), ('superadmin', 'Super Admin')], default='atendente', max_length=20),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambientes', to='api.tipoambiente'),
        ),
        migrations.CreateModel(
            name='MaterialSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('PISO', 'Piso'), ('PAREDE', 'Parede'), ('TETO', 'Teto'), ('RODAPE', 'Rodapé'), ('SOLEIRA', 'Soleira'), ('PEITORIL', 'Peitoril'), ('ESQUADRIA', 'Esquadria'), ('VIDRO', 'Vidro'), ('PORTA', 'Porta'), ('FERRAGEM', 'Ferragem'), ('INST_ELETRICA', 'Inst. Elétrica'), ('INST_COMUNICACAO', 'Inst. Comunicação')], max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default='PENDENTE', max_length=10)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='api.ambiente')),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_aprovados', to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='api.marca')),
            ],
            options={
                'verbose_name': 'Material do Ambiente',
                'verbose_name_plural': 'Materiais do Ambiente',
                'ordering': ['ambiente_id', 'item'],
                'unique_together': {('ambiente', 'item')},
            },
        ),
    ]
