# Generated by Django 5.2.7 on 2025-10-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_marca_tipoambiente_alter_usuario_cargo_ambiente_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='categoria',
            field=models.CharField(choices=[('PRIVATIVA', 'Unidade Privativa'), ('COMUM', 'Área Comum'), ('EXTERNA', 'Área Externa')], default='PRIVATIVA', max_length=20),
        ),
    ]
