# Generated by Django 5.2.7 on 2025-10-18 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ambiente_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='observacoes_gerais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DescricaoMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('marcas', models.TextField()),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descricao_marcas', to='api.projeto')),
            ],
            options={
                'verbose_name': 'Descrição de Marca',
                'verbose_name_plural': 'Descrição das Marcas',
            },
        ),
    ]
