# Generated by Django 5.2.7 on 2025-10-28 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_projeto_observacoes_gerais_descricaomarca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='api.projeto'),
        ),
    ]
