# Generated by Django 5.2.7 on 2025-10-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ambiente_projeto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambiente',
            options={'ordering': ['nome_do_ambiente'], 'verbose_name': 'Ambiente', 'verbose_name_plural': 'Ambientes'},
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='projeto',
        ),
        migrations.AddField(
            model_name='projeto',
            name='ambientes',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='api.ambiente'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tipo_do_projeto',
            field=models.CharField(choices=[('RESIDENCIAL', 'Residencial'), ('COMERCIAL', 'Comercial'), ('INDUSTRIAL', 'Industrial')], max_length=50),
        ),
    ]
