# Generated by Django 5.2.7 on 2025-10-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_ambiente_options_remove_ambiente_projeto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='nome_do_ambiente',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
