# Generated by Django 5.2.7 on 2025-10-28 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_ambiente_nome_do_ambiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricaomarca',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome_do_projeto',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
