# Generated by Django 5.2.7 on 2025-10-29 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_descricaomarca_projeto_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialspec',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='materialspec',
            name='projeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='api.projeto'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='materialspec',
            unique_together={('projeto', 'ambiente', 'item')},
        ),
    ]
