# Generated by Django 5.2.7 on 2025-10-29 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_materialspec_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.projeto'),
        ),
    ]
