# Generated by Django 5.2.7 on 2025-10-29 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_log_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='projeto',
        ),
    ]
