# Generated by Django 5.2.7 on 2025-10-29 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_log_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialspec',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='api.projeto'),
        ),
    ]
