# Generated by Django 5.2.7 on 2025-10-29 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_materialspec_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api.projeto'),
        ),
    ]
