# Generated by Django 5.2.7 on 2025-10-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_log_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='nome_do_ambiente',
            field=models.CharField(max_length=100),
        ),
    ]
