# Generated by Django 5.2.7 on 2025-10-31 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_ambiente_nome_do_ambiente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descricaomarca',
            options={'verbose_name': 'Descrição de Marca Global', 'verbose_name_plural': 'Descrição das Marcas Globais'},
        ),
        migrations.RemoveField(
            model_name='descricaomarca',
            name='projeto',
        ),
    ]
