# Generated by Django 5.2.7 on 2025-11-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_descricaomarca_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descricaomarca',
            options={'verbose_name': 'Descrição de Marca', 'verbose_name_plural': 'Descrição das Marcas'},
        ),
        migrations.AlterModelOptions(
            name='modelodocumento',
            options={'verbose_name': 'Modelo de Documento', 'verbose_name_plural': 'Modelos de Documento'},
        ),
        migrations.AddField(
            model_name='modelodocumento',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='api.projeto'),
        ),
    ]
