# Generated by Django 5.2.7 on 2025-11-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_descricaomarca_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricaomarca',
            name='material',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='materialspec',
            name='item',
            field=models.CharField(max_length=30),
        ),
    ]
