# Generated by Django 5.2.7 on 2025-11-25 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_descricaomarca_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente',
            name='esquadria',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='ferragem',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='guia_de_cores',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='inst_comunicacao',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='inst_eletrica',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='parede',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='peitoril',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='piso',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='porta',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='rodape',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='soleira',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='teto',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='vidro',
        ),
    ]
